//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegWeb.Saude.Aplicacao.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAD_TBL_CONTROLEUNIMED
    {
        public decimal COD_CONTROLEUNIMED { get; set; }
        public System.DateTime DAT_GERACAO { get; set; }
        public string COD_IDENTIFICACAO { get; set; }
        public string NOM_PARTICIP { get; set; }
        public Nullable<System.DateTime> DAT_NASCIMENTO { get; set; }
        public string COD_SEXO { get; set; }
        public Nullable<long> CPF { get; set; }
        public string ACOMODACAO { get; set; }
        public string DES_PLANO { get; set; }
        public Nullable<System.DateTime> ENVIO_UNIMED { get; set; }
        public string TIPO { get; set; }
        public string USU_GERACAO { get; set; }
        public Nullable<System.DateTime> DT_HIST { get; set; }
        public string COD_UNIMED { get; set; }
        public Nullable<System.DateTime> DAT_ADESAO { get; set; }
        public string COD_PLANO_CESP { get; set; }
        public short COD_EMPRS { get; set; }
        public int NUM_MATRICULA { get; set; }
        public string SUB_MATRICULA { get; set; }
        public Nullable<System.DateTime> DAT_CANCELAMENTO { get; set; }
        public string COBRANCA_MEMORIAL { get; set; }
        public string NUMERO_UNIMED { get; set; }
        public Nullable<int> NUMERO_VIA { get; set; }
        public string NOM_MAE_EMPRG { get; set; }
        public string TITULAR { get; set; }
        public string DCR_ESTCV { get; set; }
        public string DCR_GRADPC { get; set; }
        public string COD_UNDFD_EMPRG { get; set; }
        public Nullable<System.DateTime> DAT_INI_PERIODO { get; set; }
        public Nullable<System.DateTime> DAT_FIN_PERIDO { get; set; }
        public string NUM_CI_EMPRG { get; set; }
    }
}
