//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegWeb.Saude.Aplicacao.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class REEMB_FRMCIA
    {
        public string HDRDATHOR { get; set; }
        public string HDRCODUSU { get; set; }
        public string HDRCODETC { get; set; }
        public string HDRCODPGR { get; set; }
        public short COD_EMPRS { get; set; }
        public int NUM_RGTRO_EMPRG { get; set; }
        public Nullable<short> DIG { get; set; }
        public Nullable<short> NUM_MATR_SUB { get; set; }
        public Nullable<short> DIG_MATR_SUB { get; set; }
        public string NOME { get; set; }
        public Nullable<decimal> VLR_MEDCTO { get; set; }
        public Nullable<decimal> VLR_REEMB { get; set; }
        public long PROTOCOLO { get; set; }
        public Nullable<System.DateTime> DATA_ARQUIVO { get; set; }
        public string MRC_LANC_MEDCTR { get; set; }
        public Nullable<System.DateTime> DATA_CREDITO { get; set; }
        public decimal ID_REG { get; set; }
    }
}
