//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegWeb.Saude.Aplicacao.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAU_TBL_VALORCARTUNIMED
    {
        public decimal ID_REG { get; set; }
        public string COD_PLANO { get; set; }
        public string DES_PLANO { get; set; }
        public Nullable<decimal> INCLUSAO { get; set; }
        public Nullable<decimal> SEGUNDA_VIA { get; set; }
        public Nullable<decimal> RENOVACAO { get; set; }
        public Nullable<System.DateTime> DAT_INICIO_VIGENCIA { get; set; }
        public Nullable<System.DateTime> DAT_FIM_VIGENCIA { get; set; }
        public string USU_INCLUSAO { get; set; }
    }
}
