//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegWeb.Saude.Aplicacao.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAU_TB_SERV_AND
    {
        public string COD_HOSP { get; set; }
        public string COD_SERV { get; set; }
        public string DESCRICAO { get; set; }
        public Nullable<decimal> VALOR { get; set; }
        public Nullable<decimal> PVALOR { get; set; }
        public Nullable<decimal> AVALOR { get; set; }
        public Nullable<decimal> VPROPOSTO { get; set; }
        public Nullable<decimal> PORCENTAGEM { get; set; }
        public Nullable<decimal> PPORCENTAGEM { get; set; }
        public Nullable<decimal> APORCENTAGEM { get; set; }
        public Nullable<decimal> PPROPOSTA { get; set; }
        public Nullable<decimal> DESCONTO { get; set; }
        public Nullable<System.DateTime> DTREAJUSTE { get; set; }
        public Nullable<System.DateTime> PDTREAJUSTE { get; set; }
        public Nullable<System.DateTime> ADTREAJUSTE { get; set; }
        public Nullable<System.DateTime> DTREAJUSTEPROP { get; set; }
    }
}
