//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegWeb.Saude.Aplicacao.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAU_TBL_CARGA_REALIZADA
    {
        public decimal COD_CARGA { get; set; }
        public System.DateTime DAT_EXEC { get; set; }
        public decimal COD_CONVENENTE { get; set; }
        public decimal COD_TAB_MAT_MED { get; set; }
        public System.DateTime DAT_VIG { get; set; }
        public string NM_ARQ_IMPORT { get; set; }
        public string NM_USU { get; set; }
        public string HOST_USU { get; set; }
        public long TOTAL_INCLUIDO { get; set; }
        public long TOTAL_NAO_INCLUIDO { get; set; }
    
        public virtual TB_CONVENENTE TB_CONVENENTE { get; set; }
        public virtual TB_TAB_RECURSO TB_TAB_RECURSO { get; set; }
    }
}
