//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegWeb.Saude.Aplicacao.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAU_TBL_EXT_UTIL_DADGER_LOG
    {
        public System.DateTime HDRDATHOR { get; set; }
        public string HDRCODUSU { get; set; }
        public string DAT_REF { get; set; }
        public short COD_EMPRS { get; set; }
        public int NUM_RGTRO_EMPRG { get; set; }
        public System.DateTime DAT_MOVIMENTO { get; set; }
        public int NUM_IDNTF_RPTANT { get; set; }
        public string IDC_INIBE_EXT_ANTIGO { get; set; }
        public string IDC_INIBE_EXT_ATUAL { get; set; }
    }
}
