//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegWeb.Saude.Aplicacao.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAU_TBL_QTDE_MATMED
    {
        public decimal COD_RECURSO { get; set; }
        public int QTD { get; set; }
        public System.DateTime DAT_INIVIG { get; set; }
        public Nullable<System.DateTime> DAT_FIMVIG { get; set; }
        public string COD_ACAO { get; set; }
        public System.DateTime DTH_ACAO { get; set; }
        public string DESC_USERAPL { get; set; }
        public string DESC_PROGRAMA { get; set; }
        public string DESC_MAQREDE { get; set; }
        public string DESC_USEROS { get; set; }
        public string DESC_MAQTERM { get; set; }
    
        public virtual TB_RECURSO TB_RECURSO { get; set; }
    }
}
