//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegWeb.Saude.Aplicacao.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CENTRO_CUSTO
    {
        public Nullable<short> EMPRESA { get; set; }
        public string DS_CCUSTO { get; set; }
        public string SG_CCUSTO { get; set; }
        public decimal NUM_ORGAO { get; set; }
        public string COD_PLANO { get; set; }
        public string CCUSTO_DEB_UTIL { get; set; }
        public string CCUSTO_CRE_UTIL { get; set; }
        public string CCUSTO_DEB_GLOSA { get; set; }
        public string CCUSTO_CRE_GLOSA { get; set; }
        public string AUX_DEB_UTIL { get; set; }
        public string AUX_CRE_UTIL { get; set; }
        public string AUX_DEB_GLOSA { get; set; }
        public string AUX_CRE_GLOSA { get; set; }
        public string IR_ACEITA_LANC { get; set; }
        public string COD_TAB { get; set; }
    }
}
