//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegWeb.Saude.Aplicacao.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TAB_RECURSO
    {
        public TB_TAB_RECURSO()
        {
            this.TB_COND_CONTRAT = new HashSet<TB_COND_CONTRAT>();
            this.TB_COND_CONTRAT1 = new HashSet<TB_COND_CONTRAT>();
            this.TB_COND_CONTRAT2 = new HashSet<TB_COND_CONTRAT>();
            this.TB_COND_CONTRAT3 = new HashSet<TB_COND_CONTRAT>();
            this.TB_COND_CONTRAT4 = new HashSet<TB_COND_CONTRAT>();
            this.TB_VAL_RECURSO = new HashSet<TB_VAL_RECURSO>();
            this.SAU_TBL_CARGA_REALIZADA = new HashSet<SAU_TBL_CARGA_REALIZADA>();
            this.SAU_TBL_CLASSE_PORT_VIG = new HashSet<SAU_TBL_CLASSE_PORT_VIG>();
            this.SAU_TBL_CONV_PORTE_VIG = new HashSet<SAU_TBL_CONV_PORTE_VIG>();
        }
    
        public decimal COD_TAB_RECURSO { get; set; }
        public short COD_UM { get; set; }
        public string DES_TAB_RECURSO { get; set; }
        public System.DateTime DAT_IMPLANTACAO { get; set; }
        public string TIP_RECURSO { get; set; }
        public string IDC_CBHPM { get; set; }
        public Nullable<decimal> VAL_UCO { get; set; }
        public Nullable<decimal> PCT_BANDA_APLIC { get; set; }
        public string TPACOD { get; set; }
        public Nullable<System.DateTime> DAT_ULT_PROCESSO { get; set; }
        public Nullable<decimal> VLR_FILME_RADIO { get; set; }
    
        public virtual ICollection<TB_COND_CONTRAT> TB_COND_CONTRAT { get; set; }
        public virtual ICollection<TB_COND_CONTRAT> TB_COND_CONTRAT1 { get; set; }
        public virtual ICollection<TB_COND_CONTRAT> TB_COND_CONTRAT2 { get; set; }
        public virtual ICollection<TB_COND_CONTRAT> TB_COND_CONTRAT3 { get; set; }
        public virtual ICollection<TB_COND_CONTRAT> TB_COND_CONTRAT4 { get; set; }
        public virtual ICollection<TB_VAL_RECURSO> TB_VAL_RECURSO { get; set; }
        public virtual ICollection<SAU_TBL_CARGA_REALIZADA> SAU_TBL_CARGA_REALIZADA { get; set; }
        public virtual ICollection<SAU_TBL_CLASSE_PORT_VIG> SAU_TBL_CLASSE_PORT_VIG { get; set; }
        public virtual ICollection<SAU_TBL_CONV_PORTE_VIG> SAU_TBL_CONV_PORTE_VIG { get; set; }
    }
}
