//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegWeb.Saude.Aplicacao.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TIPO_COND_CONTRAT
    {
        public TB_TIPO_COND_CONTRAT()
        {
            this.TB_COND_CONTRAT = new HashSet<TB_COND_CONTRAT>();
            this.TB_TIPO_COND_CONV = new HashSet<TB_TIPO_COND_CONV>();
        }
    
        public decimal COD_TIPO_COND_CONT { get; set; }
        public string DES_TIPO_COND_CONT { get; set; }
    
        public virtual ICollection<TB_COND_CONTRAT> TB_COND_CONTRAT { get; set; }
        public virtual ICollection<TB_TIPO_COND_CONV> TB_TIPO_COND_CONV { get; set; }
    }
}
