//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegWeb.Previdencia.Aplicacao.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class AAT_TBL_BOLETO
    {
        public AAT_TBL_BOLETO()
        {
            this.AAT_TBL_BOLETO_ITEM = new HashSet<AAT_TBL_BOLETO_ITEM>();
            this.PRE_TBL_CONTRIB_ESPORADICA = new HashSet<PRE_TBL_CONTRIB_ESPORADICA>();
        }
    
        public long COD_BOLETO { get; set; }
        public string NUM_DOCTO { get; set; }
        public short COD_EMPRS { get; set; }
        public int NUM_RGTRO_EMPRG { get; set; }
        public Nullable<short> NUM_DIVR_EMPRG { get; set; }
        public int NUM_DCMCOB_BLPGT { get; set; }
        public string NOM_EMPR { get; set; }
        public System.DateTime DAT_VENCT_LCEMP { get; set; }
        public decimal VLR_DOCTO { get; set; }
        public short CALC_DIGITO { get; set; }
        public string TXT_FIX1 { get; set; }
        public string TXT_FIX2 { get; set; }
        public string TXT_FIX3 { get; set; }
        public string TXT_FIX4 { get; set; }
        public short COD_BANCO { get; set; }
        public string LOCAL_PAGTO { get; set; }
        public string CEDENTE { get; set; }
        public string LIN_DIGITAVEL { get; set; }
        public System.DateTime DT_PROCESSAMENTO { get; set; }
        public string INSTRUCOES1 { get; set; }
        public string INSTRUCOES2 { get; set; }
        public string INSTRUCOES3 { get; set; }
        public string INSTRUCOES4 { get; set; }
        public string INSTRUCOES5 { get; set; }
        public string DCR_ENDER_EMPRG { get; set; }
        public string BAIRRO_EMPRG { get; set; }
        public string COD_CEP_EMPRG { get; set; }
        public string NOM_CIDRS_EMPRG { get; set; }
        public string COD_UNDFD_EMPRG { get; set; }
        public string COD_BARRAS { get; set; }
        public string TXT_FIXO_ECT1 { get; set; }
        public string TXT_FIXO_ECT2 { get; set; }
        public string TXT_FIXO_ECT3 { get; set; }
        public string TXT_FIXO_ECT4 { get; set; }
        public string TXT_FIXO_ECT5 { get; set; }
        public string TXT_FIXO_ECT6 { get; set; }
        public Nullable<short> NUM_LOTE { get; set; }
        public string CODBARRAS_ECT { get; set; }
        public short SEQ_POSTAGEM { get; set; }
        public string LOG_INCLUSAO { get; set; }
        public System.DateTime DTH_INCLUSAO { get; set; }
        public string LOG_EXCLUSAO { get; set; }
        public Nullable<System.DateTime> DTH_EXCLUSAO { get; set; }
        public Nullable<short> COD_BOLETO_TIPO { get; set; }
        public long NUM_CPF { get; set; }
        public short COD_DIGITO_BANCO { get; set; }
        public string AGENCIA { get; set; }
        public string COD_CEDENTE { get; set; }
        public string DCR_ESPECIEDOC { get; set; }
        public string DCR_ACEITE { get; set; }
        public string DCR_USOBANCO { get; set; }
        public string DCR_CARTEIRA { get; set; }
        public string DCR_ESPECIE { get; set; }
        public string DCR_QUANTIDADE { get; set; }
        public string DCR_OBSERVACAO { get; set; }
        public Nullable<short> COD_BOLETO_SUBTIPO { get; set; }
    
        public virtual ICollection<AAT_TBL_BOLETO_ITEM> AAT_TBL_BOLETO_ITEM { get; set; }
        public virtual ICollection<PRE_TBL_CONTRIB_ESPORADICA> PRE_TBL_CONTRIB_ESPORADICA { get; set; }
    }
}
