//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegWeb.Previdencia.Aplicacao.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADESAO_PLANO_PARTIC_FSS
    {
        public ADESAO_PLANO_PARTIC_FSS()
        {
            this.HIST_PART_CAPIT_FSS = new HashSet<HIST_PART_CAPIT_FSS>();
        }
    
        public int NUM_MATR_PARTF { get; set; }
        public short NUM_PLBNF { get; set; }
        public System.DateTime DAT_INI_ADPLPR { get; set; }
        public short COD_TPPCP { get; set; }
        public short COD_SITPAR { get; set; }
        public Nullable<short> QTD_CTB_ADPLPR { get; set; }
        public Nullable<short> QTD_NCTBV_ADPLPR { get; set; }
        public Nullable<short> QTD_NCTBI_ADPLPR { get; set; }
        public Nullable<System.DateTime> DAT_ULTCTB_ADPLPR { get; set; }
        public Nullable<System.DateTime> DAT_FIM_ADPLPR { get; set; }
        public Nullable<System.DateTime> DAT_PRVFIMPP_ADPLPR { get; set; }
        public Nullable<short> TIP_OPCTRIBIR_ADPLPR { get; set; }
        public Nullable<System.DateTime> DAT_OPCTRIBIR_ADPLPR { get; set; }
        public Nullable<short> QTD_IDADELEG_ADPLPR { get; set; }
        public Nullable<System.DateTime> DAT_AVLATUAR_ADPLPR { get; set; }
        public Nullable<decimal> VLR_RMBAC_ADPLPR { get; set; }
        public Nullable<decimal> VLR_VAEBP_ADPLPR { get; set; }
        public Nullable<decimal> VLR_VAEBT_ADPLPR { get; set; }
        public Nullable<short> COD_EMPINSTITUIDOR_ADPLPR { get; set; }
        public Nullable<System.DateTime> DAT_ENVEXT_ADPLPR { get; set; }
        public Nullable<System.DateTime> DAT_OPCITT_ADPLPR { get; set; }
    
        public virtual EMPRESA EMPRESA { get; set; }
        public virtual PARTICIPANTE_FSS PARTICIPANTE_FSS { get; set; }
        public virtual PLANO_BENEFICIO_FSS PLANO_BENEFICIO_FSS { get; set; }
        public virtual ICollection<HIST_PART_CAPIT_FSS> HIST_PART_CAPIT_FSS { get; set; }
    }
}
