//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegWeb.Previdencia.Aplicacao.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class AFASTAMENTO
    {
        public short COD_EMPRS { get; set; }
        public int NUM_RGTRO_EMPRG { get; set; }
        public System.DateTime DAT_INAFT_AFAST { get; set; }
        public Nullable<System.DateTime> DAT_PRVFA_AFAST { get; set; }
        public Nullable<System.DateTime> DAT_FMAFT_AFAST { get; set; }
        public short COD_TIPAFT { get; set; }
        public string COD_GRUPO_CID { get; set; }
        public string COD_ITEM_CID { get; set; }
    
        public virtual EMPREGADO EMPREGADO { get; set; }
        public virtual TIPO_AFASTAMENTO TIPO_AFASTAMENTO { get; set; }
    }
}
