//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegWeb.Previdencia.Aplicacao.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAD_TBL_CTRLDEV_CORRESP
    {
        public decimal ID_REG { get; set; }
        public Nullable<decimal> NUM_CONTRATO { get; set; }
        public Nullable<decimal> COD_EMPRS { get; set; }
        public Nullable<decimal> MATRICULA { get; set; }
        public Nullable<decimal> NUM_REP { get; set; }
        public string NOME { get; set; }
        public string ENDERECO { get; set; }
        public string COMPLEMENTO { get; set; }
        public string NUMERO { get; set; }
        public string BAIRRO { get; set; }
        public string MUNICIPIO { get; set; }
        public string UF { get; set; }
        public string CEP { get; set; }
        public Nullable<decimal> ID_TIPODOCUMENTO { get; set; }
        public Nullable<System.DateTime> DATAPOSTAGEM { get; set; }
        public Nullable<System.DateTime> DATADEVOLUCAO { get; set; }
        public Nullable<decimal> ID_TIPOMOTIVODEVOLUCAO { get; set; }
        public Nullable<System.DateTime> REENVIO { get; set; }
        public string TEMPO_PRAZO { get; set; }
    }
}
