//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegWeb.Previdencia.Aplicacao.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAD_TBL_CONTROLECASSI
    {
        public decimal ID_REG { get; set; }
        public string EMPRESA { get; set; }
        public string MATRICULA { get; set; }
        public string SUB_MATRICULA { get; set; }
        public string NOM_PARTICIP { get; set; }
        public string COD_IDENTIFICACAO { get; set; }
        public string TITULAR { get; set; }
        public string PARENTESCO { get; set; }
        public Nullable<System.DateTime> DATAMOVITACAO { get; set; }
        public string CODIGOCASSI { get; set; }
        public string NUMEROCARTERINHA { get; set; }
        public string TIPO_OBS { get; set; }
        public Nullable<System.DateTime> DT_ENVIO { get; set; }
        public string TIPOMOVIMETACAO { get; set; }
        public string EXECUTADOPOR { get; set; }
        public string COBRANCA_MEMORIAL { get; set; }
        public Nullable<System.DateTime> DAT_ADESAO { get; set; }
        public Nullable<System.DateTime> DT_HIST { get; set; }
        public string ACOMODACAO { get; set; }
        public string CPF { get; set; }
    }
}
