//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegWeb.Previdencia.Aplicacao.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARGOS
    {
        public CARGOS()
        {
            this.EMPREGADO = new HashSet<EMPREGADO>();
        }
    
        public int NUM_CARGO { get; set; }
        public string DCR_CARGO { get; set; }
        public string COD_ORIGEM_CARGO { get; set; }
        public Nullable<short> COD_EMPRS { get; set; }
    
        public virtual ICollection<EMPREGADO> EMPREGADO { get; set; }
        public virtual EMPRESA EMPRESA { get; set; }
    }
}
