//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegWeb.Previdencia.Aplicacao.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class COTACAO_MES_UM
    {
        public short COD_UM { get; set; }
        public System.DateTime DAT_CMESUM { get; set; }
        public Nullable<decimal> VLR_CMESUM { get; set; }
        public Nullable<decimal> PCT_CMESUM { get; set; }
        public Nullable<System.DateTime> DAT_INC_ALT_CMESUM { get; set; }
    
        public virtual UNIDADE_MONETARIA UNIDADE_MONETARIA { get; set; }
    }
}
