//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegWeb.Previdencia.Aplicacao.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOTIVO_DESLIG_FSS
    {
        public MOTIVO_DESLIG_FSS()
        {
            this.EMPREGADO = new HashSet<EMPREGADO>();
        }
    
        public short COD_MTDSL { get; set; }
        public string DCR_MTDSL { get; set; }
        public string COD_ORIGEM_MTDSL { get; set; }
    
        public virtual ICollection<EMPREGADO> EMPREGADO { get; set; }
    }
}
