//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegWeb.Previdencia.Aplicacao.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORGAO
    {
        public ORGAO()
        {
            this.EMPREGADO = new HashSet<EMPREGADO>();
        }
    
        public int NUM_ORGAO { get; set; }
        public string NOM_ORGAO { get; set; }
        public string COD_ORGAO { get; set; }
        public short COD_EMPRS { get; set; }
        public short NUM_FILIAL { get; set; }
        public string COD_ESTADO { get; set; }
        public string COD_MUNICI { get; set; }
        public string DCR_ENDER_ORGAO { get; set; }
        public Nullable<int> NUM_ENDER_ORGAO { get; set; }
        public string DCR_COMPL_ORGAO { get; set; }
        public string NOM_CIDRS_ORGAO { get; set; }
        public string COD_UNDFD_ORGAO { get; set; }
        public Nullable<int> COD_CEP_ORGAO { get; set; }
        public string COD_DDD_ORGAO { get; set; }
        public Nullable<int> NUM_TELEF_ORGAO { get; set; }
        public string NOM_BAIRRO_ORGAO { get; set; }
        public string COD_ORIGEM_ORGAO { get; set; }
        public Nullable<short> ATOCODATRIBUTOORGAO { get; set; }
        public Nullable<int> PAICOD { get; set; }
        public string NOM_PAIS_ORGAO { get; set; }
    
        public virtual ICollection<EMPREGADO> EMPREGADO { get; set; }
        public virtual MUNICIPIO MUNICIPIO { get; set; }
    }
}
