//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegWeb.Previdencia.Aplicacao.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTICIPANTE_FSS
    {
        public PARTICIPANTE_FSS()
        {
            this.ASSISTIDO_INSS_FSS = new HashSet<ASSISTIDO_INSS_FSS>();
            this.BENEFICIO_PARTIC_FSS = new HashSet<BENEFICIO_PARTIC_FSS>();
            this.ADESAO_PLANO_PARTIC_FSS = new HashSet<ADESAO_PLANO_PARTIC_FSS>();
        }
    
        public int NUM_MATR_PARTF { get; set; }
        public short COD_EMPRS { get; set; }
        public int NUM_RGTRO_EMPRG { get; set; }
        public Nullable<short> QTD_MSIOE_PARTF { get; set; }
        public Nullable<System.DateTime> DAT_VNCFDC_PARTF { get; set; }
        public short NUM_PATROC { get; set; }
        public string TIP_APOSEN_PARTF { get; set; }
        public Nullable<System.DateTime> DAT_ADMPAT_PARTF { get; set; }
        public string MRC_APINSS_PARTF { get; set; }
        public Nullable<decimal> VLR_APINSS_PARTF { get; set; }
        public Nullable<System.DateTime> DAT_APINSS_PARTF { get; set; }
        public Nullable<decimal> VLR_ATUINS_PARTF { get; set; }
        public Nullable<System.DateTime> DAT_ATUINS_PARTF { get; set; }
        public Nullable<short> COD_ESPBNF { get; set; }
        public Nullable<decimal> PCT_APINSS_PARTF { get; set; }
        public Nullable<System.DateTime> DAT_INSCINSS_PARTF { get; set; }
        public string TIP_CFRSBF_PARTF { get; set; }
        public string MRC_DESABEXTRSV_PARTF { get; set; }
        public string MRC_REQINSC_PARTF { get; set; }
        public Nullable<short> PRICOD { get; set; }
    
        public virtual ICollection<ASSISTIDO_INSS_FSS> ASSISTIDO_INSS_FSS { get; set; }
        public virtual ICollection<BENEFICIO_PARTIC_FSS> BENEFICIO_PARTIC_FSS { get; set; }
        public virtual EMPREGADO EMPREGADO { get; set; }
        public virtual PATROCINADORA_FSS PATROCINADORA_FSS { get; set; }
        public virtual ICollection<ADESAO_PLANO_PARTIC_FSS> ADESAO_PLANO_PARTIC_FSS { get; set; }
    }
}
