//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegWeb.Previdencia.Aplicacao.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRE_TBL_ARQ_PATROCINA_LINHA
    {
        public PRE_TBL_ARQ_PATROCINA_LINHA()
        {
            this.PRE_TBL_ARQ_PATROCINA_CRITICA = new HashSet<PRE_TBL_ARQ_PATROCINA_CRITICA>();
            this.PRE_TBL_ARQ_PAT_DEMONSTRA_DET = new HashSet<PRE_TBL_ARQ_PAT_DEMONSTRA_DET>();
        }
    
        public long COD_ARQ_PAT_LINHA { get; set; }
        public int COD_ARQ_PAT { get; set; }
        public long NUM_LINHA { get; set; }
        public short TIP_LINHA { get; set; }
        public Nullable<int> NUM_HASH_LINHA { get; set; }
        public string COD_EMPRS { get; set; }
        public string NUM_RGTRO_EMPRG { get; set; }
        public string DADOS { get; set; }
        public Nullable<System.DateTime> DAT_IMPORTADO { get; set; }
    
        public virtual PRE_TBL_ARQ_PATROCINA PRE_TBL_ARQ_PATROCINA { get; set; }
        public virtual ICollection<PRE_TBL_ARQ_PATROCINA_CRITICA> PRE_TBL_ARQ_PATROCINA_CRITICA { get; set; }
        public virtual ICollection<PRE_TBL_ARQ_PAT_DEMONSTRA_DET> PRE_TBL_ARQ_PAT_DEMONSTRA_DET { get; set; }
    }
}
