//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegWeb.Previdencia.Aplicacao.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRE_TBL_ARQ_PAT_DEMONSTRA_DET
    {
        public long COD_DEMO_DET { get; set; }
        public int COD_ARQ_PAT_DEMO { get; set; }
        public string TIP_LANCAMENTO { get; set; }
        public string TIP_CRED_DEB { get; set; }
        public Nullable<short> COD_EMPRS { get; set; }
        public Nullable<long> NUM_RGTRO_EMPRG { get; set; }
        public Nullable<int> COD_VERBA { get; set; }
        public string DCR_LANCAMENTO { get; set; }
        public Nullable<decimal> VLR_LANCAMENTO { get; set; }
        public Nullable<long> COD_ARQ_PAT_LINHA { get; set; }
        public System.DateTime DTH_INCLUSAO { get; set; }
        public string LOG_INCLUSAO { get; set; }
        public string COD_VERBA_PATROCINA { get; set; }
        public Nullable<System.DateTime> DTH_AUTORIZADO { get; set; }
        public string LOG_AUTORIZADO { get; set; }
        public Nullable<System.DateTime> DTH_IMPORTADO { get; set; }
    
        public virtual PRE_TBL_ARQ_PAT_DEMONSTRA PRE_TBL_ARQ_PAT_DEMONSTRA { get; set; }
        public virtual PRE_TBL_ARQ_PATROCINA_LINHA PRE_TBL_ARQ_PATROCINA_LINHA { get; set; }
    }
}
