//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegWeb.Previdencia.Aplicacao.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRE_TBL_ACAO_VR_TIPLTO
    {
        public PRE_TBL_ACAO_VR_TIPLTO()
        {
            this.PRE_TBL_DEPOSITO_JUDIC = new HashSet<PRE_TBL_DEPOSITO_JUDIC>();
            this.PRE_TBL_ACAO_JUDIC = new HashSet<PRE_TBL_ACAO_JUDIC>();
        }
    
        public short COD_TIPLTO { get; set; }
        public string DESC_TIPLTO { get; set; }
        public Nullable<System.DateTime> DT_INI_VIG_TIPLTO { get; set; }
        public Nullable<System.DateTime> DT_FIN_VIG_TIPLTO { get; set; }
    
        public virtual ICollection<PRE_TBL_DEPOSITO_JUDIC> PRE_TBL_DEPOSITO_JUDIC { get; set; }
        public virtual ICollection<PRE_TBL_ACAO_JUDIC> PRE_TBL_ACAO_JUDIC { get; set; }
    }
}
