//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegWeb.Previdencia.Aplicacao.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRE_TBL_ARQ_AREA
    {
        public PRE_TBL_ARQ_AREA()
        {
            this.PRE_TBL_ARQ_ENV_REPASSE = new HashSet<PRE_TBL_ARQ_ENV_REPASSE>();
            this.PRE_TBL_ARQ_ENVIO = new HashSet<PRE_TBL_ARQ_ENVIO>();
            this.PRE_TBL_ARQ_ENVIO1 = new HashSet<PRE_TBL_ARQ_ENVIO>();
        }
    
        public short COD_ARQ_AREA { get; set; }
        public string DCR_ARQ_AREA { get; set; }
        public string DCR_ARQ_SUB_AREA { get; set; }
    
        public virtual ICollection<PRE_TBL_ARQ_ENV_REPASSE> PRE_TBL_ARQ_ENV_REPASSE { get; set; }
        public virtual ICollection<PRE_TBL_ARQ_ENVIO> PRE_TBL_ARQ_ENVIO { get; set; }
        public virtual ICollection<PRE_TBL_ARQ_ENVIO> PRE_TBL_ARQ_ENVIO1 { get; set; }
    }
}
