//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegWeb.Previdencia.Aplicacao.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRE_TBL_ARQ_SALDO_FUNDO
    {
        public int COD_SALDO_FUNDO { get; set; }
        public short ANO_REF { get; set; }
        public short MES_REF { get; set; }
        public short COD_GRUPO_EMPRS { get; set; }
        public Nullable<short> NUM_PLBNF { get; set; }
        public decimal VLR_SALDO_FUNDO { get; set; }
        public System.DateTime DTH_INCLUSAO { get; set; }
        public string LOG_INCLUSAO { get; set; }
        public Nullable<System.DateTime> DTH_EXCLUSAO { get; set; }
        public string LOG_EXCLUSAO { get; set; }
    }
}
