//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegWeb.Previdencia.Aplicacao.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRE_TBL_ARQ_ENVIO
    {
        public PRE_TBL_ARQ_ENVIO()
        {
            this.PRE_TBL_ARQ_ENV_REPASSE = new HashSet<PRE_TBL_ARQ_ENV_REPASSE>();
            this.PRE_TBL_ARQ_ENVIO_HIST = new HashSet<PRE_TBL_ARQ_ENVIO_HIST>();
        }
    
        public int COD_ARQ_ENVIO { get; set; }
        public short COD_ARQ_ENVIO_TIPO { get; set; }
        public Nullable<int> COD_ARQ_SUB_TIPO { get; set; }
        public string DCR_ARQ_ENVIO { get; set; }
        public string DCR_ARQ_EXT { get; set; }
        public Nullable<short> ANO_REF { get; set; }
        public Nullable<short> MES_REF { get; set; }
        public Nullable<short> COD_GRUPO_EMPRS { get; set; }
        public Nullable<short> COD_ARQ_AREA_ORIG { get; set; }
        public Nullable<short> COD_ARQ_AREA_DEST { get; set; }
        public byte[] DAT_ARQUIVO { get; set; }
        public string DCR_CAMINHO_ARQUIVO { get; set; }
        public Nullable<int> COD_ARQ_ENVIO_PAI { get; set; }
        public System.DateTime DTH_INCLUSAO { get; set; }
        public string LOG_INCLUSAO { get; set; }
        public Nullable<System.DateTime> DTH_EXCLUSAO { get; set; }
        public string LOG_EXCLUSAO { get; set; }
        public Nullable<short> COD_ACAO_ENVIO { get; set; }
    
        public virtual PRE_TBL_ARQ_AREA PRE_TBL_ARQ_AREA { get; set; }
        public virtual PRE_TBL_ARQ_AREA PRE_TBL_ARQ_AREA1 { get; set; }
        public virtual ICollection<PRE_TBL_ARQ_ENV_REPASSE> PRE_TBL_ARQ_ENV_REPASSE { get; set; }
        public virtual PRE_TBL_GRUPO_EMPRS PRE_TBL_GRUPO_EMPRS { get; set; }
        public virtual ICollection<PRE_TBL_ARQ_ENVIO_HIST> PRE_TBL_ARQ_ENVIO_HIST { get; set; }
        public virtual PRE_TBL_ARQ_ENVIO_TIPO PRE_TBL_ARQ_ENVIO_TIPO { get; set; }
    }
}
