//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegWeb.Previdencia.Aplicacao.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_DESC_PLANO_CONTAS
    {
        public string COD_PLANO_CONTAS { get; set; }
        public string DES_PLANO_CONTAS { get; set; }
        public string DS_HIST_DIARIO { get; set; }
    }
}
