//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegWeb.Previdencia.Aplicacao.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SCR_DEPARA_AUTOPATROC
    {
        public decimal COD_EMPRS_ORIGEM { get; set; }
        public decimal NUM_RGTRO_EMPRG { get; set; }
        public decimal COD_EMPRS_DESTINO { get; set; }
        public string FL_EXCLUSAO_TOTAL { get; set; }
        public string VD_PATROC { get; set; }
        public string VD_PARTIC { get; set; }
    }
}
