//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegWeb.Intranet.Aplicacao.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class FCESP_EXT_AMH_EXCECAO_LOG
    {
        public decimal ID_LOG { get; set; }
        public short COD_EMPRS { get; set; }
        public long NUM_RGTRO_EMPRG { get; set; }
        public Nullable<long> NUM_CPF_EMPRG { get; set; }
        public Nullable<int> NUM_IDNTF_RPTANT { get; set; }
        public string TP_ACAO { get; set; }
        public string USER_INC { get; set; }
        public Nullable<System.DateTime> DATA_INC { get; set; }
    }
}
