//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegWeb.Financeira.Aplicacao.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class AAT_TBL_BOLETO_SUBTIPO
    {
        public AAT_TBL_BOLETO_SUBTIPO()
        {
            this.AAT_TBL_BOLETO = new HashSet<AAT_TBL_BOLETO>();
        }
    
        public short COD_BOLETO_SUBTIPO { get; set; }
        public short COD_BOLETO_TIPO { get; set; }
        public string DCR_BOLETO_SUBTIPO { get; set; }
    
        public virtual ICollection<AAT_TBL_BOLETO> AAT_TBL_BOLETO { get; set; }
        public virtual AAT_TBL_BOLETO_TIPO AAT_TBL_BOLETO_TIPO { get; set; }
    }
}
