//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegWeb.Financeira.Aplicacao.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class AAT_TBL_RET_DEB_CONTA_MOTIVO
    {
        public AAT_TBL_RET_DEB_CONTA_MOTIVO()
        {
            this.AAT_TBL_RET_DEB_CONTA = new HashSet<AAT_TBL_RET_DEB_CONTA>();
        }
    
        public string COD_MOTIVO { get; set; }
        public string DESC_MOTIVO { get; set; }
    
        public virtual ICollection<AAT_TBL_RET_DEB_CONTA> AAT_TBL_RET_DEB_CONTA { get; set; }
    }
}
