//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegWeb.Financeira.Aplicacao.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTD010
    {
        public string CTD_FILIAL { get; set; }
        public string CTD_ITEM { get; set; }
        public string CTD_CLASSE { get; set; }
        public string CTD_NORMAL { get; set; }
        public string CTD_DESC01 { get; set; }
        public string CTD_DESC02 { get; set; }
        public string CTD_DESC03 { get; set; }
        public string CTD_DESC04 { get; set; }
        public string CTD_DESC05 { get; set; }
        public string CTD_BLOQ { get; set; }
        public string CTD_DTBLIN { get; set; }
        public string CTD_DTBLFI { get; set; }
        public string CTD_DTEXIS { get; set; }
        public string CTD_DTEXSF { get; set; }
        public string CTD_ITLP { get; set; }
        public string CTD_ITPON { get; set; }
        public string CTD_BOOK { get; set; }
        public string CTD_ITSUP { get; set; }
        public string CTD_RES { get; set; }
        public string CTD_CRGNV1 { get; set; }
        public string CTD_CRGNV2 { get; set; }
        public string CTD_RGNV3 { get; set; }
        public string CTD_CLOBRG { get; set; }
        public string CTD_ACCLVL { get; set; }
        public string CTD_ITVM { get; set; }
        public string CTD_ITRED { get; set; }
        public string CTD_ACATIV { get; set; }
        public string CTD_ATOBRG { get; set; }
        public string CTD_ACAT01 { get; set; }
        public string CTD_AT01OB { get; set; }
        public string CTD_ACAT02 { get; set; }
        public string CTD_AT02OB { get; set; }
        public string CTD_ACAT03 { get; set; }
        public string CTD_AT03OB { get; set; }
        public string CTD_ACAT04 { get; set; }
        public string CTD_AT04OB { get; set; }
        public string CTD_TPO04 { get; set; }
        public string CTD_TPO01 { get; set; }
        public string CTD_TPO02 { get; set; }
        public string CTD_TPO03 { get; set; }
        public string D_E_L_E_T_ { get; set; }
        public decimal R_E_C_N_O_ { get; set; }
        public decimal R_E_C_D_E_L_ { get; set; }
    }
}
