//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegWeb.Financeira.Aplicacao.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTT010
    {
        public string CTT_FILIAL { get; set; }
        public string CTT_CUSTO { get; set; }
        public string CTT_CLASSE { get; set; }
        public string CTT_NORMAL { get; set; }
        public string CTT_DESC01 { get; set; }
        public string CTT_DESC02 { get; set; }
        public string CTT_DESC03 { get; set; }
        public string CTT_DESC04 { get; set; }
        public string CTT_DESC05 { get; set; }
        public string CTT_BLOQ { get; set; }
        public string CTT_DTBLIN { get; set; }
        public string CTT_DTBLFI { get; set; }
        public string CTT_DTEXIS { get; set; }
        public string CTT_DTEXSF { get; set; }
        public string CTT_CCLP { get; set; }
        public string CTT_CCPON { get; set; }
        public string CTT_BOOK { get; set; }
        public string CTT_TIPO00 { get; set; }
        public string CTT_CCSUP { get; set; }
        public string CTT_TIPO01 { get; set; }
        public string CTT_RES { get; set; }
        public string CTT_CRGNV1 { get; set; }
        public string CTT_RGNV2 { get; set; }
        public string CTT_RGNV3 { get; set; }
        public string CTT_STATUS { get; set; }
        public string CTT_FILMAT { get; set; }
        public string CTT_MAT { get; set; }
        public decimal CTT_PERCAC { get; set; }
        public decimal CTT_PERFPA { get; set; }
        public string CTT_NOME { get; set; }
        public string CTT_ENDER { get; set; }
        public string CTT_BAIRRO { get; set; }
        public string CTT_CEP { get; set; }
        public string CTT_ESTADO { get; set; }
        public string CTT_MUNIC { get; set; }
        public string CTT_TIPO { get; set; }
        public string CTT_CEI { get; set; }
        public decimal CTT_VALFAT { get; set; }
        public decimal CTT_RETIDO { get; set; }
        public string CTT_LOCAL { get; set; }
        public string CTT_OCORRE { get; set; }
        public string CTT_ITOBRG { get; set; }
        public string CTT_CLOBRG { get; set; }
        public string CTT_ACITEM { get; set; }
        public string CTT_ACCLVL { get; set; }
        public string CTT_CCVM { get; set; }
        public string CTT_CCRED { get; set; }
        public string CTT_OPERAC { get; set; }
        public string CTT_CSINCO { get; set; }
        public decimal CTT_PEREMP { get; set; }
        public string CTT_RECFAT { get; set; }
        public string CTT_CODMUN { get; set; }
        public string CTT_ACAT04 { get; set; }
        public string CTT_ACATIV { get; set; }
        public string CTT_ATOBRG { get; set; }
        public string CTT_ACAT01 { get; set; }
        public string CTT_AT01OB { get; set; }
        public string CTT_ACAT02 { get; set; }
        public string CTT_AT02OB { get; set; }
        public string CTT_ACAT03 { get; set; }
        public string CTT_AT03OB { get; set; }
        public string CTT_AT04OB { get; set; }
        public string CTT_RHEXP { get; set; }
        public string CTT_TPO01 { get; set; }
        public string CTT_TPO02 { get; set; }
        public string CTT_TPO03 { get; set; }
        public string CTT_TPO04 { get; set; }
        public string CTT_INTRES { get; set; }
        public string CTT_RESERV { get; set; }
        public string CTT_TPLOT { get; set; }
        public string CTT_TIPO2 { get; set; }
        public string CTT_CEI2 { get; set; }
        public string CTT_FPAS { get; set; }
        public string CTT_CODTER { get; set; }
        public decimal CTT_FAP { get; set; }
        public decimal CTT_PERRAT { get; set; }
        public string CTT_ICTPAT { get; set; }
        public string CTT_CNAE { get; set; }
        public string CTT_TPINCT { get; set; }
        public string CTT_NRINCT { get; set; }
        public string CTT_TPINPR { get; set; }
        public string CTT_NRINPR { get; set; }
        public string D_E_L_E_T_ { get; set; }
        public decimal R_E_C_N_O_ { get; set; }
        public decimal R_E_C_D_E_L_ { get; set; }
    }
}
