//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegWeb.Financeira.Aplicacao.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class CV0010
    {
        public string CV0_FILIAL { get; set; }
        public string CV0_PLANO { get; set; }
        public string CV0_ITEM { get; set; }
        public string CV0_CODIGO { get; set; }
        public string CV0_DESC { get; set; }
        public string CV0_CLASSE { get; set; }
        public string CV0_NORMAL { get; set; }
        public string CV0_ENTSUP { get; set; }
        public string CV0_BLOQUE { get; set; }
        public string CV0_DTIBLQ { get; set; }
        public string CV0_DTFBLQ { get; set; }
        public string CV0_DTIEXI { get; set; }
        public string CV0_DTFEXI { get; set; }
        public string CV0_CFGLIV { get; set; }
        public string CV0_LUCPER { get; set; }
        public string CV0_PONTE { get; set; }
        public string CV0_ECVM { get; set; }
        public string CV0_ECRED { get; set; }
        public string D_E_L_E_T_ { get; set; }
        public decimal R_E_C_N_O_ { get; set; }
    }
}
