//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegWeb.Financeira.Aplicacao.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUN_TBL_ATU_CC
    {
        public decimal ID_REG { get; set; }
        public short COD_EMPRS { get; set; }
        public int NUM_RGTRO_EMPRG { get; set; }
        public Nullable<int> NUM_IDNTF_RPTANT { get; set; }
        public Nullable<long> NUM_CPF_EMPRG { get; set; }
        public Nullable<short> COD_BANCO { get; set; }
        public Nullable<int> COD_AGBCO { get; set; }
        public string TIP_CTCOR_EMPRG { get; set; }
        public string NUM_CTCOR_EMPRG { get; set; }
        public string NOME { get; set; }
        public string NOME_ARQ { get; set; }
    }
}
