//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegWeb.Financeira.Aplicacao.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class GB_INTEGR_CT
    {
        public short CD_EMPRESA { get; set; }
        public short CD_PLANO { get; set; }
        public System.DateTime DT_GERACAO_ARQUIVO { get; set; }
        public string NO_ARQUIVO { get; set; }
        public System.DateTime DT_CD_MOV { get; set; }
        public int NR_CD_MOV { get; set; }
        public int SQ_LANC_MOV { get; set; }
        public Nullable<short> CD_ATIVIDADE { get; set; }
        public string CD_CONTA { get; set; }
        public string CD_AUXILIAR { get; set; }
        public string CD_CCUSTO { get; set; }
        public string TP_DOCUM { get; set; }
        public Nullable<int> NR_DOCUM { get; set; }
        public Nullable<System.DateTime> DT_COMPET { get; set; }
        public Nullable<decimal> VL_LANCAMENTO { get; set; }
        public string IR_DEB_CRED { get; set; }
        public string CD_HISTORICO { get; set; }
        public string DS_HIST_DIARIO { get; set; }
        public string IR_CRITICA_MOV { get; set; }
        public Nullable<int> CD_REDUZIDA { get; set; }
    }
}
