//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegWeb.Financeira.Aplicacao.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIST_CADASTRO_FSS
    {
        public decimal NUM_SQNCL_HISCAD { get; set; }
        public Nullable<int> NUM_IDNTF_RPTANT { get; set; }
        public Nullable<int> NUM_IDNTF_DPDTE { get; set; }
        public Nullable<System.DateTime> DAT_INIVIG_HISCAD { get; set; }
        public Nullable<System.DateTime> DAT_FIMVIG_HISCAD { get; set; }
        public Nullable<short> COD_EMPRS { get; set; }
        public Nullable<int> NUM_RGTRO_EMPRG { get; set; }
        public Nullable<short> COD_BANCO { get; set; }
        public Nullable<int> COD_AGBCO { get; set; }
        public string NUM_CTCOR_HISCAD { get; set; }
        public string TIP_PROCES_HISCAD { get; set; }
        public string TIP_CTCOR_HISCAD { get; set; }
        public Nullable<long> NUM_CPFCTC_HISCAD { get; set; }
        public string NOM_SEGTIT_HISCAD { get; set; }
    
        public virtual AGENCIA AGENCIA { get; set; }
        public virtual DEPENDENTE DEPENDENTE { get; set; }
        public virtual EMPREGADO EMPREGADO { get; set; }
    }
}
