//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegWeb.Financeira.Aplicacao.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDCTR
    {
        public int NUM_LOTE { get; set; }
        public string IDREC { get; set; }
        public string STATUS { get; set; }
        public string XNUMCT { get; set; }
        public string XTPLIQ { get; set; }
        public string XTPMED { get; set; }
        public string DTREF { get; set; }
        public string DTVENC { get; set; }
        public string NOSSONUMERO { get; set; }
        public string PRODUT { get; set; }
        public string CCUSTO { get; set; }
        public string PROGRAMA { get; set; }
        public string PATROCINADOR { get; set; }
        public string SUBMASSA { get; set; }
        public string PROJETO { get; set; }
        public Nullable<decimal> VALMED { get; set; }
        public string DTINCL { get; set; }
        public string DTINTEG { get; set; }
        public string TIPOPAR { get; set; }
        public short COD_ASSOC { get; set; }
        public int COD_CONVENENTE { get; set; }
        public short COD_EMPRS { get; set; }
        public int NUM_RGTRO_EMPRG { get; set; }
        public Nullable<int> NUM_MATR_PARTF { get; set; }
        public int NUM_IDNTF_RPTANT { get; set; }
        public int NUM_IDNTF_DPDTE { get; set; }
        public string BANCO { get; set; }
        public string AGENCIA { get; set; }
        public string DVAGE { get; set; }
        public string NUMCON { get; set; }
        public string DVNUMCON { get; set; }
        public string COMPENSAVEL { get; set; }
        public string EVENTO { get; set; }
        public string ANO_FATURA { get; set; }
        public Nullable<decimal> NUM_SEQ_FATURA { get; set; }
        public Nullable<decimal> NUM_SEQ_ATEND { get; set; }
        public Nullable<decimal> NUM_SEQ_ITEM { get; set; }
        public string ERRO_STATUS3 { get; set; }
        public Nullable<short> TP_PROC { get; set; }
        public string MRC_DBT_ATM { get; set; }
        public string TP_BLT { get; set; }
        public string FLAG_JUDIC { get; set; }
        public string DSC_VERBA { get; set; }
        public long SEQ_MEDCTR { get; set; }
        public string TIPOFOR { get; set; }
        public string MRC_PGTO_APRT { get; set; }
        public string NF_FATURA_CONVENENTE { get; set; }
    }
}
